project:
  type: book
  resources:
    - CNAME

book:
  title: "Climate Change und Rural Depopulation"
  author: "Jakob Arendt"
  date: today
  site-url: https://mathesis.jakobarendt.com
  repo-url: https://github.com/jakobarendt/mathesis-depop
  repo-actions: [issue,edit,source]
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - ch-1-introduction.qmd
    - ch-2-rel-literature.qmd
    - ch-3-methodology.qmd
    - ch-4-data.qmd
    - ch-5-results.qmd
    - ch-6-conclusion.qmd
    - references.qmd
  appendices:
    - appx-1-pop-data.qmd
    - appx-2-weat-data.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    papersize: a4
    geometry:
      - top=25mm
      - bottom=30mm
      - left=40mm
      - right=25mm
      - footskip=15mm
    mainfont: "Times New Roman"
    sansfont: "Arial"
    fontsize: 12pt
    linestretch: 1.5
    # documentclass: scrbook
    # cite-method: natbib
    # header-includes: |
      # \bibliographystyle{ecta}
  docx:
    papersize: a4
    mainfont: "Times New Roman"
    fontsize: 12pt
