project:
  type: book

book:
  title: "Climate Change und Rural Depopulation"
  author: "Jakob Arendt"
  date: today
  chapters:
    - index.qmd
    - introduction.qmd
    - rel-literature.qmd
    - data.qmd
    - methodology.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrbook