project:
  type: book
  resources:
    - CNAME

book:
  title: "Climate Change und Rural Depopulation"
  author: "Jakob Arendt"
  date: today
  site-url: https://mathesis.jakobarendt.com
  repo-url: https://github.com/jakobarendt/mathesis-depop
  repo-actions: [issue,edit,source]
  chapters:
    - index.qmd
    - introduction.qmd
    - rel-literature.qmd
    - data.qmd
    - methodology.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf: default
#    documentclass: scrbook