project:
  type: book
  resources:
    - CNAME

book:
  title: "Climate Change und Rural Depopulation"
  author: "Jakob Arendt"
  date: today
  site-url: https://mathesis.jakobarendt.com
  repo-url: https://github.com/jakobarendt/mathesis-depop
  repo-actions: [issue,edit,source]
  chapters:
    - index.qmd
    - ch-1-introduction.qmd
    - ch-2-rel-literature.qmd
    - ch-3-data.qmd
    - ch-4-methodology.qmd
    - ch-5-results.qmd
    - ch-6-conclusion.qmd
    - references.qmd
  appendices:
    - appx-1-pop-data.qmd
    - appx-2-weat-data.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf: default
    # documentclass: scrbook
    # cite-method: natbib
    # header-includes: |
      # \bibliographystyle{ecta}
  docx: default
