# Historic Population Data and its Georeferences {#sec-AppxPopData}

-   grid weather data is based on the WGS84 geodetic reference datum and geographic coordinate reference system (CRS), therefore shapes are retrieved as projections that are referenced to the same datum or they are transformed accordingly

-   **difference again between geodetic reference datum and geographic coordinate reference system?? (and also own sheets of notes)**

-   **add that it is not actually based on the standard WGS84, but rather on the WGS84 for computer usage (where x and y axes are interchanged) see sf documentation for a brief explanation** @package-sf **; OGC:CRS84 is considered the "traditional" GIS order, supposed standard is to have longitude as the first coordinate, and latitude as the second** cite package documentation for command *sf::st_transform()*

-   shapes retrieved via GISCO API and special cases delivered on EUROSTAT project website

-   however the special cases (Greece, Ireland, and Turkey) are shapes that are projections for different Geodetic CRS, and they are transformed accordingly (to EPSG:4326 - WGS84)

-   transformations may produce some inaccuracies:

    -   Greece by 1.0 m (from EPSG:3035 - ETRS89-extended / LAEA Europe)
    -   Ireland accuracy unknown (from EPSG:4258 - ETRS89)
    -   Turkey by 2.0 m (from EPSG:4230 - ED50)
    -   more information on [**epsg.io**](epsg.io)

-   Neither the population data shapefiles nor the weather grid data specify which version of the WGS84 coordinate reference system they refer to.
    However, any potential version differences, whether they be caused by improved accuracy of the datum or by tectonic plate movements, are considered to have little to no influence on this research set up.
    The dimensions and sizes of the geographical units under investigation are disproportionately bigger than any of the potential datum shifts caused by the differing WGS84 versions.
    Besides, potential misalignents due to tectonic plate movement are unlikely as this investigation focuses on a single continent, and almost all of the investigated land mass lies on the same principal tectonic plates (with Macaronesia and Iceland being only minor exceptions, **are there any other exceptions?? --\> plot map quickly with leaflet**)

```{r}
#| eval: false

shapes_2011 |> filter(startsWith(CNTR_LAU_ID, "LU")) |> ggplot() + geom_sf(aes(fill = ifelse(LAU_NAME == "Eschweiler" | LAU_NAME == "Wiltz", "Highlight", "Default"))) + scale_fill_manual(values = c("Highlight" = "red", "Default" = "grey")) +
  theme(legend.position = "none")
shapes_2012 |> filter(startsWith(CNTR_LAU_ID, "LU")) |> ggplot() + geom_sf()

```

| Country | Observations (Individ. File) | Geo Version (Individ. File) |
|---------|------------------------------|-----------------------------|
| AT      | 2357                         | 1 Jan 2012                  |
| BE      | 589                          | 1 Jan 2012                  |
| BG      | 4619                         | not specified               |
| CH      | 2499                         | not specified               |
| CY      | 614                          | not specified               |
| CZ      | 6251                         | 1 Jan 2012                  |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |
|         |                              |                             |

: Countries, their observations and geolocation characteristics

The R script [`prep-pop-data.R`](./prep-pop-data.R) documents all of the steps taken as part of the cleaning, reorganizing and georeferecing of the historic LAU population data.

ToDo: Add scatterplot for representing correlation between historic population figures and population figures delivered with shapefiles to represent strong correlation between historic interpolation and real figures.
