# Introduction

How have climate and its changes shaped the growth and distribution of population across European municipalities in the last decades?
In this investigation, I attempt to identify the causal relationship between population growth and climate and I try to quantify the effect the latter has had on the former.

Tremendous advances in computational power have enabled the research community to develop an understanding of the climate and its underlying physics, that has never been more profound.
Similarly, the proofs that demonstrate how a multitude of human activity is the very likely cause for modern-day climate change through the continuous emission of greenhouse gases have never been less clear.
While this shows that we have relatively good knowledge of what humans are capable of doing to the climate, the opposite direction seems less clear: We still stand a lot to gain from a better understanding of what the climate and its changes are doing to humans and human societies, not least as this varies greatly with the specific population, area and circumstances considered.

One such socioeconomic aspect likely influenced by the climate is the development of population figures in defined regions.
Particularly the effects on smaller regions are interesting to estimate as the climate variation across space tends to decrease with the size of the area a region covers.
The climate of the smaller region can then often be more stringently defined, which, in turn, allows for a clearer attribution of climatic characteristics to the region's outcomes.
In the context of political boundaries, such small spatial units are present in almost every country and they are called "commune", "county", "municipality" or something similar.

How the population of a country or continent is distributed across its communes and municipalities, and how and what makes this distribution evolve matters for a multitude of reasons.
The population size of a municipality heavily determines its political influence and leverage.
Consider that, for example, many of the most populous cities end up becoming capitals that house the most powerful political instutions of their nations.
It also determines their access to (supra-)national funds as the distribution of public resources is often decided by population size.

The population size of a municipality matters also for its economic constitution: In a theoretical scenario without economies of scale and where economic output of a country is evenly distributed across all its inhabitants such that its empirical GDP per capita exhibits a uniform distribution, total economic production of a populous city will be much higher than that of a small town with few inhabitants.
This would result in much higher local resources for consumption, investment and taxation.
In reality, many of these conditions assumed do not hold true -- consumption, investment, taxation and other redistributional measures are not anymore as much confined locally as was the case before the industrialisation and the development of modern government.
Nevertheless, other conditions can still make a vast difference in economic opportunities of urban and rural areas, no matter the wealth of the overall country: For example, economies of scale do indeed differ across space and along with a much bigger and likely more heterogenous workforce, this often allows urban areas to achieve higher diversification in economic sectors and more specialisation than their rural counterparts.
These differences in economic structures between urban and rural areas can have significant consequences for their inhabitants.
Among the ones most prevalent in the public debate are disparities in access to infrastructure, particularly healthcare, transport and other services essential to everyday life.

With the above considerations in mind, this investigation is motivated by the need for a thorough understanding of the relationship between climate and population development.
Such an understanding is esssential for informed policymaking to further develop adequate and well-targeted policies that effectively strengthen mitigation of, adaptation to and resilience against climate change, ensuring sustainable population and, consequently, sustainable economic development.
One concrete examplary use-case of insights on the effect of climate on population is how urbanisation and city growth also increase humans' vulnerabilty towards climate change, in particular due to increases in precipitation runoff intensity and hot extremes [@ipcc-ar6-synthesis-report, pp. 50 and 98].
If this and other investigations can conclude that climate change also causes population shifts from rural to urban areas over time, it might indicate a self-perpetuating or even self-exacerbating circle in which population becomes more urban due to climate change but also more vulnerable to climate change because climate change made it more urban in the first place.

-   Consider IPCC AR6 synthesis report: Urbanisation and city growth increase people's vulnerability towards climate change consequences (e.g. exposure to heat extremes and precipitation runoff intensity). If it can be concluded that, on the other hand, climate change also causes population shifts from rural to urban areas, this might lead to self-perpetuating, "vicious", cycle.

The key methodology I use to prove and estimate a causal effect of climate on municipal population distribution are econometric panel regressions with different functional forms.
I consider linear as well as non-linear effects of climate and also make use of fixed effects to estimate population response functions to climate, and I benchmark these panel approaches against cross-sectional and hybrid (long-differences) approaches.
For the panel and hybrid approaches, I exploit the time series dimension of the municipalities' weather and population data that allows me to apply fixed effects to correct for time-invariant unobserved municipality-specific characteristics potentially confounding the climate-population relationship.
\[TODO plug in here sentence if I do forecasting as well\]

The remainder of this thesis paper is organised as follows: In @sec-Literature I discuss parts of the literature touching upon my research question, particularly investigations that use econometric methodology to identify effects of climate on socioeconomic outcomes.
Then a chapter on the methodology used in my investigation follows [@sec-Methodology] follows, along with a chapter on the data sets [@sec-Data].
@Sec-Results lays out the results of my work and @sec-Conclusion concludes.
Appendices with further details on the population ([-@sec-AppxPopData]) and weather ([-@sec-AppxWeatData]) are also provided.

-   One/two sentences about the remaining strucuture of the thesis.
    "The remainder of this thesis paper is organized as follows..." (do not forget to mention the appendix) OR "The chapter following this introduction..."

-   \[Research question / Overall perspective:\] Estimation of response functions, quantifying the effect of temperature and precipitation on population development

\[Further notes for myself:\]

-   mention *IPCC reports* when discussing urgency of climate change as a topic in public debate (i.e. consequences/scenarios when no actions are taken)
-   **Social outcomes** as key word
-   unobservables differentiating spatial units and also correlated with weather/climate may cause bias - use of panel model should help to correct for this ("By exploiting the time series nature of the historical population and weather data, I am able to account for many unobserved biases potentially confounding the effects estimation. The models mainly used for this estimation are ...**TODO**)
-   (Mention results)

The first aim is that this backward-looking investigation, considering climatic and societal outcomes decades back to the 1960s, demonstrates how long the warmig planet has already had an impact on society, even in industrialised countries that are often considered as less affected than developing ones.
The second aim, resulting out of the first one, is that the longer historical perspective underlines once more the relevance and urgency for climate action, and supports a better informed and more targeted approach to (climate) policymaking, in particular for regions suffering from depopulation.

Make us of a variety of different regression models and estimate climate impacts with cross-sectional, panel and hybrid approaches.

\[Optional:\]

-   A great part of investments in public infrastructure, whether be it for schools, hospitals, transport or something else, takes place in densely populated areas. Likely, these areas also often dominate the considerations for adapting such infrastructure to increasing temperatures, more extreme weather events and other consequences of climate change. By showing that rural areas are equally or even more vulnerable to climate change than their urban counterparts, I am able to underscore their significance when deciding where to allocate resources for climate change adaptation.
