# Related Literature {#sec-Literature}

At a defined location during a specific period in time, there are three main factors that determine the growth or decline of its human population: birth rate, mortality rate and migration.
In theory, their relationships with population growth are relatively clear: if one of these three determinants changes while keeping the other two constant, population growth will change.[^ch-2-rel-literature-1]
For example, if a defined population experiences no migration, and has new children at the same rate as deaths, it does neither grow nor decline---it remains stable.

[^ch-2-rel-literature-1]: While an increase in the location's birth rate implies an increase in its population growth ceteris paribus, the effect of the mortality rate is the opposite.
    As regards migration ceteris paribus, immigration causes the location's population to grow, whereas emigration causes it to shrink.

In practise, however, the way that these factors determine population growth is much more complex and convoluted.
First, they can move simultaneously and can, consequently, cancel each other out.
For example, a country may experience a decrease in its birth rate, but its population would remain stable if it faced an increase in immigration at the same magnitude as the decrease in its birth rate.
Second, birth, mortality, and migration can exhibit interdependencies among themselves.
For example, when comparing population growth across societies in different locations and with different economic preconditions, an economically poorer society might be incentivised to have more children to make up the comparably higher mortality or the fewer retirement provisions caused by its comparably fewer resources and economic endowments.
Third, they can be subject to conscious decisions by individuals or society, or they can be the direct consequences of their circumstances, the environment or the events they find themselves exposed to.
For example, the decision to migrate could be one imposed forcefully by a natural disaster or one considerately taken with a longer-term view and justified by living preferences.
**\[TODO: Fourth point here?\]**

When investigating the relationship between climate and population growth, the aforementioned aspects make it hard to perfectly distil all the underlying causal pathways, infer about their interactions and understand how they might combine to form the overall effect.
As a researcher, one then typically has to make the decision to either look at individual links of these causal chains in isolation or to consider the aggregate relationship from a more macroscopic perspective.
Even though the econometric analysis in this thesis aims to do the latter, the following describes a few of the causal pathways that are likely to drive the climate-population relationship and introduce heterogeneity for urban and rural preconditions into that relationship.

Consider first the first-order or direct demographic effects of climate---situations in which climate has shown to have a direct effect on total population, birth, mortality or migration.
For example, @heutel-etal-2021-mortality-effects-us-regions investigate heterogeneous effects of climate on mortality and find that increases in temperature affect mortality differently, depending on the current regional climate.
**\[TODO: Add sentence with further detail on the study.\]** Allowing for heterogeneity is also what this study aims, however not based on the climatic preconditions of the investigated spatial units, but rather on the preconditions they show in infrastructure and settlement characteristics.

\[TODO\] **Human health**

Safety can also have impacts on birth and death rates.
It is also a major part of what is often considered as quality of living, eventually driving human decisions to migrate or to settle.
One meta analysis aggregating the results of 55 studies in this field is from @burke-etal-2015-climate-conflict.
The authors conclude that anomalies in temperature and in rainfall

**Conflict** in their meta analysis of 55 studies on the relationship between climate and conflict that of all weather dimensions, temperature has the strongest impact on conflict.

One level more macroscopic...
**Migration** @bohramishra-etal-2014-permanent-migration-climate perform a panel analysis, considering the effect of temperature and precipitation onto lagged shares of permanent emigration out of sub-national regions \["probability to migrate"\].
The authors find that the overall effects onto emigration are stronger for temperature than for precipitation.
They also compare this to lagged shares of permanent emigration resulting from natural disasters and find that \[...\].

**Urbanisation** A study that aims to relate climate change with shifts in rural and urban population amounts is from @barrios-etal-2006-rural-urban-mig-africa.
With the help of a cross-section analysis that considers the underlying multi-period panel data only in pooled format, the authors estimate that decreasing precipitation has increased urbanisation in Sub-Saharan Africa by \[...\] for every milliliter less of rainfall \[clarify the quantitative results, also which resolution\].
Similarly, @henderson-etal-2017-cc-urbanization-africa also investigate urbanisation.

**Economic activity, growth, productivity and opportunities** Contrasting to the micro-level aspects laid out before, various studies have also tried to establish a causal relationship on the macro-level, i.e. between economic growth or activity and the climate.
Climate change profoundly and permanently alters how comparative advantages of different regions fare against each other, whether be it in natural conditions and how humans are able to live with and exploit them, or in infrastructure and other human-made (pre)conditions.
Check @kalkuhl-wenz-2020-climate-on-grp, @linsenmeier-2023-temp-econ-dev-sfd, @marbler-2024-water-econ-activity as well.
**\[Here check that economics also influence population, i.e. look into demographics literature.\]**

In other words, these above aspects and many more already have a proven relationship to climate, or at least weather.
Population reflects all these aspects to a varying degree, allowing it to be a measure combining different causal chains for identifying the effect of climate on humans on the macro-level.
As the overall approach of this investigation concerns...

**provide more background on the Henderson paper** **Relevant literature is the literature that is touching upon and relevant to my research question: How has climate shaped (or: influenced) European municipal population figures since WW2?**

\[Name & differentiate papers by economic subject area/independent variable (e.g. agriculture, conflict, economic growth & activity, migration, productivity, urbanisation) and weather variable\]

\[Name some papers (the same as mentioned just above or others) to make a differentiation by methodology, i.e. simple cross-section analysis, panel analysis, *spatial first differences* etc\]

*Cite those three mentioned in the @auffhammer-etal-2013-weather-data-econ-analysis paper:*

Among the first to introduce panel models in the context of estimation economic impacts of climate were Auffhammer, Ramanathan, and Vincent 2006; Deschenes and Greenstone 2007; Schlenker and Roberts 2009...
also quote Fisher et al (2012)

\[Consider literature in the context of these two argumentation strands & causal channels:\]

1.  Climate literature: What influences does climate have on socioeconomic outcomes and how have they been measured? (I already have some literature on this)
2.  Population literature: What has shaped population shifts and urbanization (and migration), and which role have climate and socioeconomic factors played in these shifts? How have they been measured? (Still need to find more literature on that)

\[Differentiators to other, already published, literature:\]

-   its relatively small spatial resolution
-   the time span of the underlying data going relatively far back (first period 1961)
-   its panel nature allowing for control of many unobserved confounders with repeated influence stable in magnitude in every period
-   Unique in the geographical and economic area it covers, many studies seemed to have focused more on developing countries, using nightlights as a proxy for economic development. Using data from European sources, where independent statistical and meteorological institutions responsible for collecting the data underlying this study have been, at least historically, comparably strong and reliable.
-   To my knowledge, no one has so far pursued such a climate-related analysis with this exact population data set, particular contribution with geographical area it investigates (Europe) and the spatial level of detail
-   While many other studies [e.g. @bohramishra-etal-2014-permanent-migration-climate, **check paper**] have put greater focus on migration per se--not giving deeper considerations on where people come from or where they go when a changing climate makes them move--or have mainly investigated urbanisation--i.e. considering mainly cities as object of interest in the climate-population relationship--, this investigation adds to the existing literature by giving particular attention to rural areas and their unique circumstances.

\[Further notes for myself\]

-   List literature that explore *Social Cost of Carbon (SCC)*
-   For my case, particularly the literature with a similar setup -- in terms of measures used for climate, population figure development as economic/subject area, econometric methodology making use of the additional time-dimension of the data, and the spatial dimension being relatively small (e.g. not entire countries)
-   Find literature on the temperature variability over Europe (during the last 100 years at least); also find literature on trends in annual precipitation over Europe
