# Data

The empirical analysis of the effect of climate change on population size in rural areas relies on two main data sets: Historical climate data and historical population data.
The essential characteristics of these data sources are described in this chapter.
However, both of these data sets come with peculiarities, that require further individual cleaning and preparation before joining them together and using them in the panel analysis.
The steps undertaken for their preparation are described more extensively in [@sec-AppxPopData] and [@sec-AppxWeatData], analogously.
The spatial join of the two data sets, that relates the historical population data with the weather data on the basis of their geographic locations, is discussed in the last one of the following sub-chapters (@Sec-SpatialJoin).

## Historical LAU Population Data Set {#sec-SubsecPopData}

The historical population data for European Local Administrative Units (LAUs) is available through Eurostat.
LAU is a statistical classification set out by Eurostat for referencing municipalities and other small administrative regions.
It is also just below Level 3 of Eurostat's *Nomenclature of Territorial Units for Statistics* (NUTS) classification.
The data covers LAUs of European Union (EU) member states, certain candidate and European Free Trade Association (EFTA) countries, as well as the United Kingdom, and can be downloaded from the website of the statistics authority [@eurostat-2023-lau-website].

Since LAUs are (public) Local Administrative Units, their structural constitutions and geographic extents are subject to adjustments as local, national, and European policies change.
For this investigation in particular, reforms of administrative boundaries can highly complicate the analysis of the LAUs' population figures because the statistical units lose inter- and intra-unit comparability across time periods when their spatial dimensions change.
Additionally, census time points vary among countries and regions, which complicates cross-section (intra-period) comparability as this requires unified points in time.
The collectors of the data took this into account and estimated or interpolated population figures whenever and/or wherever that was needed to construct a spatially and temporally harmonised data set.

Due to the above-mentioned persistent changes of the LAUs' administrative boundaries throughout time, their boundaries were fixed to the base year 2011 (or 2012, depending on country) to allow for comparability across time points.
Frequency and scope of modifications to the administrative boundaries was diverse among countries.
For this reason, the techniques chosen to fix the spatial attributes of the population figures to the same base year vary on a case-by-case basis, depending on the year/cohort and the country[^ch-4-data-1].
For example, for some countries and periods a backward approach was applied that adjusted only the figures of those LAUs subject to known boundary changes.
For other countries and periods however, spatial overlays of year-specific boundary maps were performed to adjust all LAU figures of an entire or even multiple time periods.
Special cases, for instance where two LAUs were combined to a single one, are also labeled with footnotes pointing to metadata distributed alongside the country-wise data tables.
The report of the data collectors outlines these adjustments for harmonisation to the same base year in more detail [@gloersen-luer-2013-report-data-collect].

[^ch-4-data-1]: In two cases, the data providers of the figures and spatial attributes were different even within the country: For Germany and the UK, fixing techniques were therefore also considered by region.

Besides space in form of the boundaries, the second dimension that needed harmonisation to ensure comparability is time.
Expectedly, countries did not collect their census data at the same points in time.
Hence, the creators of the data set aimed to collect LAU population figures for at least one year in each decade of the years 1960 to 2011, and decided to make adjustments if census collection dates were lying too far apart within a decade.
While figures for some countries were only few days apart from or exactly on the proposed reference dates and could be used directly, others had to be estimated for the reference dates with a geometric interpolation method.
Finally, population data for the reference dates January 1st of 1961, 1971, 1981, 1991, 2001, and 2011 were derived.

In addition to the partially estimated figures to ensure their harmonisation as well as the original ones, the data is delivered with unique identifiers that can reference the figures to their geospatial attributues, more specifically vector data delivered in shapefiles.
This way, the historical population figures can be integrated into maps and other spatial analyses.
For the majority of the countries, these georeferences correspond to the *EuroBoundaryMap* [@eurogeographics-2025-euroboundarymap-website; @eurostat-2025-gisco-copyright-website] versions of the years 2011 or 2012.
The population figures were harmonised to LAU boundaries of either of the two years.
Nonetheless, some countries' LAU population figures are delivered with references to different geospatial vector data, for which the shapefiles are provided directly with the historical population data set.
Similarly, there are also exceptions regarding the spatial level of detail: For most countries, the population figures are geographically referenced to the LAU2-level that has the highest spatial resolution in Eurostat's LAU classification.
However, for some countries population data could only be estimated for the coarser LAU1-level.
While @tbl-lau-levels-maps gives a rough overview of these different characteristics of the geospatial attributes that the population figures are referenced to, @sec-AppxPopData provides more context and detail, for example which georeference base year was assumed for which country and why.

| Country             | LAU-Level | Corresponding Geographic Attributes/Maps |
|:--------------------|----------:|-----------------------------------------:|
| Greece              |      LAU1 |           Delivered with population data |
| Ireland             |      LAU2 |           Delivered with population data |
| Lithuania           |      LAU1 |                         EuroBoundaryMaps |
| Portugal            |      LAU1 |                         EuroBoundaryMaps |
| Slovenia            |      LAU1 |                         EuroBoundaryMaps |
| Turkey              |      LAU1 |           Delivered with population data |
| All other countries |      LAU2 |                         EuroBoundaryMaps |

: Types of LAU-levels and underlying sources for geospatial attributes for all countries in the data set {#tbl-lau-levels-maps}

## Weather Data

\[Discuss in this sub-chapter:\]

-   **Resolution of raster** 0.1 deg, mention also what that would be equivalent to in km (for different latitudes)
-   Raster is balanced panel of weather data (it provides repeated observations for the same units, i.e. grids, throughout multiple time points)
-   Briefly discuss publisher of the data (ECMWF), consider further information from the documentation of the grid, in particular:
    -   The number of stations that provide data for the grid and its interpolations/reanlyses and whether there were significant changes in distribution and total amount of stations
    -   Reanalysis or original station data and interpolated where needed?
    -   How is station data interpolated? (Station data is complemented by interpolation for those locations without station or with missing weather data points)
-   Mention which weather parameters are downloaded: Temperature, precipitation etc

Disadvantages of weather grid data according to @auffhammer-etal-2013-weather-data-econ-analysis: **attenuation bias** (in particular for points 1, 2 and 5)

1.  Many weather grid data products are similar in average temperatures for each of their grids, but they differ greatly in variance from these means.
2.  Measurement errors caused by spatial interpolation done by averaging for regions with missing data.
    -   Likely less of a problem for this investigation, Europe still has one of the highest densities of weather stations
    -   Rather an issue for selected areas of the grid, in particular for regions in Europe with high prevalence of weather fronts, high variance of territorial surface heights or any other circumstances causing consequential differences of weather states within a grid cell at the same time point
    -   **Important consequence:** A bias in measurement error towards more rural areas!
3.  Lack of full set of weather variables/failure to include other weather variables can lead to indeterminate OVB as correlation among different weather variables varies greatly depending on location.
4.  Spatial correlation in weather data grids can lead to multicollinearity in econometric estimation, in turn overestimating standard errors for weather variable coefficients.
    -   Only a problem for cross-section estimation? Or also for panel data?
5.  Unwanted exogeinity from artificial variation and breakpoints in weather data time series, caused by anthropogenic changes in weather station availability and other changes in methodology, strategy and management of weather data measurement and recording.
    -   Mainly a problem when investigating smaller geographic areas.
    -   Criterion: Weather station coverage does not change with (policy) intervention; here: Population figure changes should have no connection to changes in weather station coverage, i.e. might only be noticeable in countries and regions with profound and sudden systemic change such as former east block

## From Weather Data Variables to Measures of Climate and Climate Change

\[Discuss in this sub-chapter:\]

-   How are the different weather parameters aggregated on the time dimension to correspond to the time points of historical population data:
    -   "Classical" approach with decade averages of yearly mean temperature, yearly precipitation sum, and potentially other parameters?
    -   Alternatively, consider variability-based indicators (but probably more likely to measure short-term responses)
    -   Consider measures suggested in @roberts-etal-2012-agronomic-weather-measures as examples for how to aggregate weather data

\[Put main parts of chapter *Common Approaches in Climate Econometrics* in this chapter?\]

Main points from @auffhammer-etal-2013-weather-data-econ-analysis:

-   Climate as long average of weather at given location (difference between weather and climate a matter of time)
-   Differentiation between climate responses (explained by climate normals, e.g. long averages in cross-sections) and short-run weather elasticities (explained by short-term weather fluctuations)

## Mapping Climate onto Weather Data and Descriptive Evidence {#sec-SpatialJoin}

\[Discuss in this sub-chapter:\]

-   Compare size of grid (and consequently the size of its area) with the territorial size of the smallest and biggest LAU
-   Mention & cite exactextractr package
-   Provide graphics to demonstrate spatial overlay
