# Conclusion {#sec-Conclusion}

In chapter @sec-Methodology, I also provide the formal argument that allows for exploiting weather data to describe climatic states and their changes.

Potential further extensions:

- Further and better control variables, in particular for other drivers known to simultaneously influence the climate and births, mortality or migration.
- **Width of climate variables:** The variables specifying climate need to be comprehensive to ensure its exogeneity when considering the climate's impact on a population (e.g. temperature may have a significant variation in one temperature, but another climate variable that exhibits significant variation in the following period as consequence of temperature may not be captured and this becomes a problem). Typically, the different weather parameters exhibit high correlation.
  - @auffhammer-etal-2013-weather-data-econ-analysis argue for considering the entirety of available and relevant weather variables to avoid indeterminate OVB (as correlation between the weather variables themselves can highly vary in sign and magnitude for the different LAUs) **argue that correlation matrix between all available weather variables is not needed, rather look into correlations for all the LAUs (sign of OV bias depends on location. As the identifying variation is within-LAU, this needs to be accounted for - otherwise estimation of the effect of that variation will only be unbiased for some LAUs but not for all)**
- **Adaptation & Consideration of other global regions:** One aspect that might explain why this study did not find significant structural differences between urban and rural demographics' reactions towards climate change, might be that, in the sample, the communes of both types have adaptation capabilities sufficient to attenuate any such differences. Another explanation for the absence of differences in impacts could also be that the country-time trends and fixed effects induced over-control and took out too much of the variation needed to identify such different predispositions for adaptation. Two potential extensions result from this: first, it may be worth considering urban-rural differences in effects of climate on demographics for regions that have generally less infrastructure endowments and adaptation capabilities than the comparably rich European continent. Second, a yearly set up of my panel model would likely estimate effects with a much weaker correction for adaptation. If its results deviated materially from my decennial set up, it could point at a violation of the marginal treatment comparability assumption and further materialise the suspicion of over-control, or further prove that, at least within Europe, adaptation over the long term diminishes any urban-rural differences in demographic effects of climate.[^ch-6-conclusion-1]

[^ch-6-conclusion-1]: The potential violation of the marginal treatment comparability assumption in the case that the results of the yearly panel model deviate too strongly from the decennial panel model stems from the test statistic that @hsiang-2016-climate-econometrics proposes for the assumption.
    It is based on the idea that estimates of climate effects are reliable if they amount to the same in magnitude when being recovered from different methodological approaches, including cross-sections and panels at different frequencies.

Improve how the econometric models in this investigation account for overall population trends in each of the countries in the sample and in Europe as a whole.
<!--was genau meine ich denn da?!?!?-->

After all, some European countries and the continent as a whole are on the forefront of deep demographic changes that can also be observed globally.
In that regard, potential extensions for the research presented in this thesis could range from including more variables likely correlated to population figures and weather (e.g. (child) mortality rates, life expectancy) to an improved argumentation as to how such currently unobserved confounders and trends not yet explicitly specified need or need not be considered to validate the results.
Such considerations might also resemble a fruitful opportunity to test the population dynamics derived in Malthusian and post-Malthusian [e.g. @galor-weil-2000-growth-population-post-malthus] models.

- Why is this important? Why do the results matter? What consequences have the results?
- What are potential extensions of this investigation? Which areas of research needs further attention?
- Consider also: Global trend that regions that suffer most from population decreases are most supportive of right-wing populist politics.

Due to their oftentimes higher proximity to the equator as well as their significantly less resources and investment capabilities to adapt to climate change, the consequences of climate change are typically considered far more severe for developing countries than for their industrialised counterparts.
However, this analysis shows that even countries that are among the richest and furthest away from the equator are also not exempted from such consequences.

\[Limitations:\]

- Dilemma of identifying climate change vs identifying direct impacts of climate change: the long time horizon of this study satisfies the former aspect well, but not the latter. This (latter) aspect of difficulties in identifying the socioeconomic impact of climate (i.e. the causal relationship between population and climate change) is likely worsened by the fact of under-control (even other studies that panel estimation-based relied on a broad set of control variables).
- No clear differentiation between direct and belief effects, likely more modelling and additional assumptions needed (with the setup of this investigation, one way to argue that the estimates only capture direct effects would be to say that in Europe the vast majority of people may have not made their decision to move based on expectations about the climate)
