<!--
This website contains the contents of my master's thesis.
In essence, it is a [Quarto](https://quarto.org) book project in HTML output format.
Naturally, the final submission of the thesis will be rendered to PDF.

*To those that were incredibly patient with me. And to those that believed in me in those times when I did not anymore. In particular, thank you to SB and to F.*
-->

## Abstract {.unnumbered}

\[...\] This thesis is also an exercise in reproducibility in quantitative economic and social sciences.
I tested tools aimed at enhancing reproducibility and explored their usability and limitations in everyday research life, in particular tools for integrated reporting to incentivize along-text computations (**Quarto**), version control (Git) and third-party hosted computation along with open-source publishing (GitHub Actions & GitHub Pages).
The GitHub repository complementing this work contains a README.md that explains how to obtain the storage-intensive components of the input data and how to reproduce the results by executing the computations on any of the most common OS (MacOS, Ubunto, Windows).

\[Further notes to myself for abstract:\]

-   Put in short mention of econometric methodology, i.e. Pooled model, FE model, and Long-differences model
-   Put in contact details
