# Identification, Methodology and Research Design {#sec-methodology}

Isolating climate information either from directly collected weather data or partially or fully from models of the climate (e.g. reanalysis) is a non-trivial task.
Similarly non-trivial is identifying the causal impacts that climatic states described by such information can have onto societal and economic outcomes.
The following sub chapter entails a quick overview of what common climate-related identification problems look like and what econometric research designs have mostly been applied to solve them.
The sub chapters following afterward describe the specific identification problem for this study, and then argue for and specify the research design chosen for this case.

## Common Approaches in Climate Econometrics

In their comprehensive survey article of climate-related econometric methodology, @hsiang-2016-climate-econometrics provide a formal definition of climate, that underlies many empirical studies that relate climate to economic and societal variables.
In essence, climate is described by a vector $\mathbf{C}_{i \tau}$ consisting of $K$ relevant parameters indexed by $k$ that characterize a joint probability distribution $\psi ( \mathbf{C}_{i \tau} )$.
In theory, a vector $\mathbf{v}_{it}$ of random variables of weather conditions relevant to economic and societal outcomes (e.g. temperature or precipitation) at any time point $t$ within time period $\tau = [ \underline{t}, \overline{t} )$ and in space $i$ could be drawn from this distribution, such that

$$
\mathbf{v}_{it} \sim \psi ( \mathbf{C}_{i \tau} ) \quad \forall \, t \in \tau .
$$ {#eq-climate-distr}

In other words, climate is the parametrization of the joint distribution $\psi ( \cdot )$, based on which certain potential states of weather could realize during time period $\tau$ and at place $i$.
Ultimately, the goal of the econometric research design would then be to find an appropriate description $\mathbf{c}_{i \tau}$ for the theoretical parameter vector $\mathbf{C}_{i \tau}$, and to use it to then estimate its effects onto any of the outcome variables in question.
**(mention that** $\mathbf{c}_{i \tau}$ is a description of the weather during $\tau$ and give an example such as for the mean **??**)

A multitude of remarks can be drawn from this definition: First, the expected distribution of weather realizations $\psi ( \mathbf{C}_{i \tau} )$ can never be parametrized by its empirical counterpart $\psi ( \mathbf{c}_{i \tau} )$, that characterizes the distribution of realized (and, in an empirical study, observed **?** calculated if weather data set values are model-based) weather states $\mathbf{v}_{i, t \in \tau}$.
After all, the observations are measurements (or, calculations) of weather states, that could have also realized differently from the theoretical distribution.
According to the definition from @hsiang-2016-climate-econometrics, climate is not only the weather we observe, be it over a short or a long period of time, but it is also the weather that could have happened with similar probability (**??** revisit this sentence).
Thus, this definition has the advantage that it also allows for climate parameters to be derived from partly or fully theoretical or numerical models, such as reanalyses.
Second, however, the fact that the true climate is not known does not imply that realized weather cannot be used to estimate climate impacts.
After all, the observed weather characteristics $\mathbf{c}$ are still realizations conditional on climate characteristics $\mathbf{C}$, mathematically expressed as $\mathbf{c} ( \mathbf{C} )$.
This remark might be the most important one as it provides the foundation for identification of climate effects from weather data and weather variation.
Third, and this is a direct consequence of the second remark, the above definition does not impose any specific rules on which weather parameters to use for summarizing and describing climate $\mathbf{C}$, nor on the lengths of the time periods $\tau$ that should be studied.
Since $\mathbf{c} ( \mathbf{C} )$ holds, any set of parameters and any time lengths would be a description of true climate $\mathbf{C}$.
Certainly, the extent and the quality of the description would likely vary with the chosen parameters and time lengths.
As @hsiang-2016-climate-econometrics notes on the choice of parameters, the weather parameters to summarize climate have, in tendency, increased in number with each new study applying climate econometric models.
Regarding the question of which time length to consider for the climate to be described adequately, I am of the impression from the literature that this very much depends on the time lengths of the dependent (economic or social) outcome variable.
Often the same time period (or, in panels, frequency) or some preponed **(?)** or other functional form of it is chosen for the weather parameter aggregation, e.g. a yearly mean of daily average temperatures for estimating a climate effect on production that is calculated on a yearly basis.

When discussing climate econometric methodology, a differentiation between direct and indirect effects of climate on socioeconomic outcome variables is necessary.
An example for the direct effect would be that more sunburns among humans are typically caused in areas or time periods of more intense ultraviolet (UV) radiation.
In such a case, the realizations of climate, $\mathbf{c} ,$ occurring during time period $\tau$ and resulting of true climate $\mathbf{C}$, have a direct effect on the human population.
In contrast to that, the indirect effects channel via the beliefs that humans have about the climate $\mathbf{C}$, e.g. if people expect high sun exposure and intense UV radiation, some of them will buy and apply sunscreen.
These belief effects are independent of climate realizations $\mathbf{c}$, e.g. not every time an individual had expected high UV exposure and applied sunscreen, ended the weather up being in a state that allowed for high amounts of UV light to reach Earth's surface.
However, beliefs may certainly change over time due to the experience an individual makes.
Actions, $\mathbf{b},$ that are taken on the basis of these beliefs and that influence socioeconomic outcomes are therefore subject to the structure of the true climate $\mathbf{C}$ and its potential changes, expressed mathematically as $\mathbf{b} ( \mathbf{C} )$.
In addition, the mentioned experience gained over time allows the individual to adapt to changes in the structure of $\mathbf{C}$.
Such adaptation, in turn, can influence the direct effects if it includes measures that the individual undertakes and that change how climate affects the socioeconomic outcome variables.
In practice, it is often difficult to separately identify and estimate belief effects.
Similarly, adaptation, i.e. the interaction between direct and belief effects **(put this where adaptation is mentioned for the first time)**, and the interaction between different belief effects themselves can make reliable identification very complex.
No econometric research design handles all of these problems well at the same time, but rather each have their differently aligned strengths and weaknesses in accounting for them.
The different econometric research designs each come with their own strengths weaknesses in accounting for these different problems.
**(explain strategies to account for adaptation)**

Adaptation

Mention also for the sunscreen example that (assuming there is sun and the counterfactual is that people do not have/ do not apply sunscreen), it changes the socioeconomic effect of UV radiation

Generally, it is difficult to measure these two effects separately in empirical studies.

Or put adaptation here?

-   paragraph on direct and indirect (adaptation) effect

-   paragraph explaining how this links to the ATE identification introduced by Holland (1986); **see also in Bachelor's thesis for Rubin Causal Model**

-   paragraph comparing major research designs (cross-sectional, panel, long differences) with each other, including their strengths and weaknesses; also how recent developments have tried improve upon their weaknesses, i.e. spatial first differences for weaknesses in cross-section (Druckenmiller and Hsiang, 2018, Linsenmeier 2023)

-   paragraph on what else again (?)...
    I had something else

-   Internal vs. external validity (or maybe put that in the second subchapter?)

## Identification Problem and Methodology

-   Path: results.qmd Discuss causal channels of climate change (agricultural productivity, overall economic productivity and wealth levels, consequent effects on wages and living standards)
-   **Identifying variation** as a key word
-   Data generating process not well known, high potential for OVB problem (mostly in cross-sectional econometric research designs!)
-   Also, unit homogeneity assumption does not hold (very little comparability in unknown confounders for some LAUs), which makes OVB problem even harder to avoid: panel/time-series approach with adequate fixed effects as solution for this
-   Argue well for **marginal treatment comparability assumption** in time-series approach (less strongly needed for long differences); add in formula for it as well
-   Identifying assumption: Exogeneity of temperature and precipitation, i.e. identifying variation stems from temperature levels and precipitation amounts and it is assumed to be exogenous to population amounts
-   Mention mostly harmless econometrics ?
-   Considering the distinctive richness of the data, providing dependent and explanatory characteristics of the same units throughout multiple time periods, this time dimension additionally provided allows leveraging on the advantages of panels analyses vs. cross-section. In particular, fixed effects and long-differences models provide powerful capabilities to control for unobserved confounders. In this setup, they are those unobserved *time-invariant* characteristics that influence the climate-demographic causal relationship and are different among the LAUs, such as natural resources, distance to other LAUs and potential economic hubs, consequent potential for economic growth etc.
-   Long-differences, essentially a difference-in-difference approach comparing potential outcomes at two relatively distant time points, may better regard the spatially detailed yet aggregated nature of the data. After all, as the data is only available on the LAU-level, it can only provide a macroscopic insight into the decisions of the economic agents of the respective LAUs. Remember that the underlying panel data for this analysis does not follow individuals nor firms but LAUs. Hence, considering the macroscopic nature of the data and the long-run time focus of the research question, a panel model based on multiple cohorts lying relatively closely together in terms of time might take out too much of the identifying variation and correct for the wrong kinds of unobserved confounders. **bring examples for short-term and long-term unobserved confounders**

considering unobservable LAU-level characteristics particularly prevalant in the long-run, might prove a better fit to the data at hand and the research question on the long-run demographic consequences of climate change.
**include also attenuation bias and citation for mostly harmless econometrics**

## Econometric Research Design

-   Mention mostly harmless econometrics ?
-   interaction term between weather aggregates and controls??
-   balanced panel (!)
-   decennial panel model
-   one with pure means for temperatures and means of yearly precipitation sum:

$$
\begin{aligned}
\mathrm{pop}_{ict} &= \beta_{\mathrm{TS}} \, \mathrm{temp}_{ict} + g ( \mathrm{prec}_{ict} ) + \omega_i + \rho_c + \epsilon_{ict}\\
\mathrm{pop}_{ict} &= \beta_{\mathrm{TS}} \, \mathrm{temp}_{ict} + \mathrm{temp}_{ict} \cdot \pi_{i} + \pi_i + g ( \mathrm{prec}_{ict} ) + \omega_i + \rho_c + \epsilon_{ict}
\end{aligned}
$$

-   where:

    -   $\mathrm{temp}_{ict}$ denote the mean temperature of the decade preceding each population data reference time point $t$ in LAU $i$
    -   $g ( \mathrm{prec}_{ict} )$ represents different functional forms (linear, quadratic, cubic) of the average yearly precipitation sum (again of the preceding decade)
    -   $\omega_i$ are LAU-fixed effects accounting for unobservable differences correlated to the weather parameter and influencing population amounts
    -   $\rho_c$ are country-fixed effects considering country-specific unobservables
    -   $\epsilon_{ict}$ is the regression error

This model is a simple OLS model that tests whether any population differences can be attributed to differences in weather parameters.
The interaction term $\mathrm{temp}_{ict} \cdot \pi_{i}$ is included to account for the fact that the effect of temperature on population might differ between LAUs, and that this difference is not captured by the LAU-fixed effects.

-   einzelner dummy für ländlich und nicht nicht notwendig, kein Interesse
-   FEs noch: country-zeit oder zeit (ersteres wahrscheinlich besser)
-   $\delta \cdot \text{year}$ trend faktor
-   am besten log-lin model (oder alternativ first differences, wenn zu viele rausfallen weil log(0)), ansonsten beobachtungen mit 0 rausnehmen, dann halt unbalanced panel (aber das ist ok, sofern die 0 random ist)
-   2-part-modell als sonstige Lösung

Similarly, a long differences model:

$$
\begin{split}
\mathrm{pop}_{ic, t=T} - \mathrm{pop}_{ic, t=1} = \alpha &+ \beta_{\mathrm{LD}} \, ( \mathrm{temp}_{ic, t=T} - \mathrm{temp}_{ic, t=1} ) \\
&+ g ( \mathrm{prec}_{ic, t=T} - \mathrm{prec}_{ic, t=1} ) + \omega_i + \rho_c + \phi_{ic}
\end{split}
$$

-   This is a simple OLS model testing whether any changes caused by weather differences between the last and the first decade can be attributed to any population differences:
    -   $\alpha$ captures any overall changes over time relevant to all LAUs
    -   $g ( \cdot )$ again represents different functional forms for precipitation that are tested
    -   $\omega_i$ is a dummy that control for LAU-specific particularities
    -   similarly, $\rho$ is a country-specific dummy, and
    -   $\phi_{ic}$ is the regression error.
-   one with variation as implemented in Linsenmeier (2023)?
-   Interaktionsterm temp und ländlich fehlt noch

## Questions

-   Do the first panel model instead with log- or percent-growth rates, and then also introduce time-specific fixed effects?
-   Reverse causality? More populated areas are likely to have higher surface temperatures, but this cancels out with the hypotheses that hotter LAUs have population reductions, right?

Einschub:

-   nur wenn bebauungsgrad konstant im LAU-FE geschluckt, aber sonst ist das ja in der gemessenen Temperatur im Grid mitgemessen

-   modellierung als discrete choice modell (tortenstücke), also wenn ein Individuum sich für ein LAU entscheidet, entscheidet es sich dann für ein kühles LAU (das in den in meinen Daten stärkeres Pop Wachstum verzeichnet)

-   landwirtschaftlich: wasser, wirtschaft&produktivität: temp

-   Correct to say: Adaptation effects are accounted for as long as adaptation happens at the same pace in each period?

-   **New:** (On adaptation) In my case, adaptation would likely lead to an attenuation bias in the effect estimations.
    For the panel model, would it be right to say that adaptations that influence the climate-socioeconomic causal relationship in a constant way over time are account for due to the time series nature of the panel model?

    -   country-FE, LAU-FE catch differences in adaptation capability of LAUs
    -   trend-variable captures influence of adaptation on climate-socioecon relationship that is constant over time (even better: trend\*LAU)
    -   fixed effects each for every year can control for adaptation effects that are irregular over time

## Personal ToDos

### General ToDos / Further Steps

-   Mention and define *social costs of carbon (SCC)*
-   Research more on non-linear effects, and how they could be argued for (and if they are needed)
-   Similarly, research more on alternative climate representations, e.g. degree days
-   Research and think about how the long differences model deals with adaptation effects
-   In Climate Econometrics, is there anything similar to the random assignment assumption that we typically have in program evaluation?
-   What about heterogenous treatment effects?
-   Search studies/give examples why population figures correlate with absolute gdp and other economic variables of the corresponding region (or at least their respective growth/decline go in the same direction)

### Points from Mostly Harmless Econometrics (not entirely sure though)

-   Mention that the choice for an individual effects model helps dealing with confounding heterogeneity that is unobserved or difficult to capture with explanatory variables at hand
-   Mention: Choice of fixed-effect model since individual-specific unobserved properties are assumed to be correlated with the other explanatory variables as well as the dependent, causing endogeneity and the known explanatory variables to be correlated with the error in the cohort-agnostic pooled model
-   **within estimator** = deviations from means estimator --\> **absorbing fixed effects**
-   Can I really assume a homoscedastic standard error? --\> would be the underlying assumption for standard within estimator
-   **Caveat:** FE estimation susceptible to attenuation bias from measurement error (very likely here as well!) --\> benchmark estimates against simple, cohort-ignorant/cohort-agnostic OLS

### Points from Koop (2008)

-   Argue why fixed effects model and not random effects model
    -   Considering the setup, LAU-specific effects might not be random and the error correlated with the explanatory variables (do a test for endogeneity? Hausman?). After all, there are very likely other variables, whether unobservable or with hardly attainable data at the small LAU resolution, that are correlated with weather and have an effect on population sizes.
    -   Also do a Lagrange multiplier/likelihood ratio test for the pooled model to see whether individual effects models are actually needed
-   **!! double check!!**: Can I really use the first-differences estimator?
    -   It is only possible to use this estimation methodology if I don't have any important time-invariant explanatory variables to include in my model equations!
    -   In the case that time-invariant explanatory variables need to be included, an alternative would be the random effects-model

### Points Johnston and DiNardo (2007)

-   Random vs FE Model - Random when individual effects not correlated with explanatory variables - FE when individual effects are correlated with explanatory variables
